version: '3'

services:
  # Database
  db:
    image:  mysql:latest
    volumes:
      - '/mysql/data:/var/lib/mysql:rw'
    restart: always
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    user : root
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    user: root
    ports:
      - '8000:80'
    restart: always
    volumes:
      - '/code:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      TAR_OPTIONS: "--no-same-owner"
    networks:
      - wpsite
networks:
  wpsite:
